### ISSUE TITLE
Setting up Stampy server

### ISSUE THREAD

**Issue by ihershkovitz** [mrstampy/Stampy#7]
Hi,
I have downloaded the zip and trying to setup the server.
but it requires a lot of external jars.
can you specify a list of the jars (preferably with download links) ?
can you provide a setup guide to run as java server application ?

Thanks 
Your help much appreciated.
Ido H

**Comment by mrstampy** [comment]
I wrote Stampy as a project to learn more about Apache Ivy, the Maven repos, and to keep my teeth sharp.  Stampy was intended to be used as a basis for a STOMP server, to be developed upon and customised.  If you are attempting to install it as a stand alone server, I would strongly recommend that you use one of the many other implementations http://stomp.github.io/implementations.html.

If you are a programmer then I would suggest using Eclipse/IntelliJ with either the Maven or Ivy plugin to fetch Stampy and the required libraries.

Alternatively you can look at the https://github.com/mrstampy/Stampy/blob/master/ivy.xml and download the jars manually from mvnrepository.com
